source 'https://github.com/CocoaPods/Specs.git'
source 'https://gitee.com/dvlproad/dvlproadSpecs'

platform :ios, '9.0'
#use_frameworks!
inhibit_all_warnings! #inhibit_warnings参数能够有效的抑制CocoaPods引入的第三方代码库产生的warning。

post_install do |installer|
    
    puts 'Determining pod project minimal deployment target'
    
    pods_project = installer.pods_project
    deployment_target_key = 'IPHONEOS_DEPLOYMENT_TARGET'
    deployment_targets = pods_project.build_configurations.map{ |config| config.build_settings[deployment_target_key] }
    minimal_deployment_target = deployment_targets.min_by{ |version| Gem::Version.new(version) }
    
    puts 'Minimal deployment target is ' + minimal_deployment_target
    puts 'Setting each pod deployment target to ' + minimal_deployment_target
    
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings[deployment_target_key] = minimal_deployment_target
        end
    end
end


target 'CJComplexUIKitDemo' do
  pod 'CQDemoKit',                '~> 0.3.0'
  #pod 'CQDemoKit',                :path => '../../../GitHub/001-UIKit-CQDemo-iOS’
  pod 'CJBaseUIKit',              :path => '../’
  pod 'CJBaseUtil',               :path => '../’
  pod 'CJBaseHelper',             :path => '../’
  pod 'CJFoundation',             :path => '../’
  pod 'CQOverlayKit'
  pod 'CJBaseEffectKit',          :subspecs => ['CJDataEmptyView', 'CJScaleHeadView']
  pod 'CJComplexUIKit/CJScrollView',        :path => '../’
  pod 'CJComplexUIKit/CJCollectionView',    :path => '../’
  pod 'CJComplexUIKit/CJHomeCollectionView',:path => '../’
  pod 'CJMenuListKit',                      :path => '../’
  pod 'CJCollectionViewFlowLayout',         :path => '../../../Gitee/UIKit-List-iOS’
  pod 'UICollectionViewCJSelectHelper',     :path => '../../../Gitee/UIKit-List-iOS’
  pod 'CQExtralItemCollectionViewDataSource',:path => '../../../Gitee/UIKit-List-iOS’
  
  pod 'AFNetworking/Reachability'
  pod 'NJKWebViewProgress'
  pod 'SVProgressHUD'
  pod 'SDCycleScrollView', '~> 1.75' #(已包括SDWebImage)原理其实就是扩大dataSource的count
  #    pod 'SDWebImage', '~> 4.0.0'
  pod 'DZNEmptyDataSet'
  pod 'MJPopupViewController', '~> 0.4'
  
  
  # 图片选择需要依赖的库
  pod 'JGActionSheet'
  pod 'CJMedia/CJUploadImagePickerUtil', '~> 0.0.7' #其中包含了对CJFile中的部分依赖
  pod 'CJNetwork/AFNetworkingBaseComponent'
  
  # 测试图片上传
  pod 'IjinbuNetwork', '~> 0.1.0' #之前有过IjinbuNetwork中有依赖CJBaseUtil的CJDevice和CJBaseUIKit的UIImage,所以这里不能使用pod，否则link错误
  pod 'CJNetwork'#,    '0.5.0'
  pod 'AFNetworking'#, '3.2.1'
end

target 'CJComplexUIKitDemoTests' do
  
end
