source 'https://github.com/CocoaPods/Specs.git'
source 'https://gitee.com/dvlproad/dvlproadSpecs'

platform :ios, '13.0'
use_frameworks!
inhibit_all_warnings! #inhibit_warnings参数能够有效的抑制CocoaPods引入的第三方代码库产生的warning。

post_install do |installer|
    
    puts 'Determining pod project minimal deployment target'
    
    pods_project = installer.pods_project
    deployment_target_key = 'IPHONEOS_DEPLOYMENT_TARGET'
    deployment_targets = pods_project.build_configurations.map{ |config| config.build_settings[deployment_target_key] }
    minimal_deployment_target = deployment_targets.min_by{ |version| Gem::Version.new(version) }
    
    puts 'Minimal deployment target is ' + minimal_deployment_target
    puts 'Setting each pod deployment target to ' + minimal_deployment_target
    
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings[deployment_target_key] = minimal_deployment_target
        end
    end
end


target 'CJComplexUIKitDemo' do
  pod 'CQDemoKit',          '~> 0.9.2',      :subspecs => ['BaseVC', 'Demo_Resource', 'Demo_DataSourceAndDelegate', 'Demo_RipeView']
  #pod 'CQDemoKit',          :path => '../../001-UIKit-CQDemo-iOS',      :subspecs => ['BaseVC', 'Demo_DataSourceAndDelegate']
  
  pod 'CJBaseUIKit',      :subspecs => ['UIColor', 'UINavigationBar', 'UIButton', 'UIImage', 'UITextField', 'CJBaseTableViewHeaderFooterView']
  pod 'CJBaseUtil',       :subspecs => ['CJDataUtil', 'CJPinyinHelper']
  pod 'CJBaseHelper',     :subspecs => ['AuthorizationCJHelper']
  pod 'CJOverlayView'
  pod 'CJBaseEffectKit'
  pod 'CJPopupAction'
  
  pod 'CJComplexUIKit',           :path => '../’
#  pod 'CJComplexUIKit/CJScrollView',      :path => '../’
#  pod 'CJComplexUIKit/CJCollectionView',  :path => '../’
#  pod 'CJComplexUIKit/CJHomeCollectionView',  :path => '../’
  
  pod 'AFNetworking/Reachability'
  pod 'SVProgressHUD'
  pod 'SDCycleScrollView', '~> 1.75' #(已包括SDWebImage)原理其实就是扩大dataSource的count
  #    pod 'SDWebImage', '~> 4.0.0'
  pod 'DZNEmptyDataSet'
  pod 'MJPopupViewController', '~> 0.4'
  
  # 测试图片上传
  pod 'IjinbuNetwork'#,  :path => '../../../Gitee/Feature-Network-iOS'
  # pod 'CQAppNetwork',   :path => '../../../Gitee/Feature-Network-iOS'
  pod 'CQImageAddDeleteListKit', :subspecs => ['AddDeletePickUpload']#,  :path => '../../../Gitee/UIKit-List-ImageAddDelete-iOS'
end

target 'CJComplexUIKitDemoTests' do
  
end
