platform :ios, '8.0'
#use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'
source 'https://gitee.com/dvlproad/dvlproadSpecs'  #这里要增加的是这条私有仓库的地址，而不是那些私有仓库里的库的地址，即如果你是增加'https://gitee.com/dvlproad/CJCustomView.git'那就错了。（之前自己犯过一次错）

inhibit_all_warnings! #inhibit_warnings参数能够有效的抑制CocoaPods引入的第三方代码库产生的warning。

target 'CJUIKitDemo' do  
  pod 'PureLayout', '~> 3.0.2'
  pod 'Masonry'
  
  pod 'MJRefresh', '~> 3.1.12'
  pod 'MBProgressHUD' #CJToast需要使用
  pod 'SVProgressHUD', '~> 2.2.2'
  pod 'OpenUDID', '~> 1.0.0'
  
  pod 'Shimmer', '~> 1.0.2' #fackBook的闪光动画
  
  
  pod 'SDCycleScrollView', '~> 1.73' #(已包括SDWebImage)原理其实就是扩大dataSource的count
  #    pod 'SDWebImage', '~> 4.0.0'
  
  pod 'MJPopupViewController', '~> 0.4'
  
  
  # 自己的库
  pod 'CJPicker', '~> 1.3.2'
  
  # 搜索功能需要使用的库
  pod 'PinYin4Objc', '~> 1.1.1'
  
  # 账号安全需要依赖的库
  pod 'SAMKeychain'
  
  # 图片选择需要依赖的库
  pod 'JGActionSheet'
  pod 'CJMedia/CJUploadImagePickerUtil', '~> 0.0.7' #其中包含了对CJFile中的部分依赖
  pod 'CJNetwork/AFNetworkingBaseComponent'
  pod 'IjinbuNetwork', '~> 0.0.5' #之前有过IjinbuNetwork中有依赖CJBaseUtil的CJDevice和CJBaseUIKit的UIImage,所以这里不能使用pod，否则link错误

  # 网页
  pod 'WebViewJavascriptBridge', '~> 6.0.2'
  
  # 基本的第三方库
  pod 'MJExtension', '~> 3.0.13'
  pod 'Mantle', '~> 2.1.0'
  
  pod 'YYText', '~> 1.0.7'
  
  pod 'NJKWebViewProgress'
  
  pod 'DZNEmptyDataSet'
end

target 'CJUIKitDemoTests' do
    #pod 'OCMock', '~> 3.4.1'

end
