platform :ios, '8.0'
#use_frameworks!

target 'CJUIKitDemo' do  
  pod 'PureLayout', '~> 3.0.2'
  pod 'Masonry', '~> 1.0.2'
  
  pod 'MJRefresh', '~> 3.1.12'
  pod 'MBProgressHUD', '~> 1.0.0' #CJToast需要使用
  pod 'SVProgressHUD', '~> 2.2.2'
  pod 'OpenUDID', '~> 1.0.0'
  
  pod 'Shimmer', '~> 1.0.2' #fackBook的闪光动画
  
  
  pod 'SDCycleScrollView', '~> 1.73' #(已包括SDWebImage)原理其实就是扩大dataSource的count
  #    pod 'SDWebImage', '~> 4.0.0'
  
  pod 'MJPopupViewController', '~> 0.4'
  
  
  # 自己的库
  pod 'CJPicker', '~> 1.3.2'
  pod 'CJPopupAction', '~> 1.4.5'
  
  # 搜索功能需要依赖的库
  pod 'NSOperationQueueUtil', '~> 0.0.1'
  # 搜索功能需要使用的库
  pod 'PinYin4Objc', '~> 1.1.1'
  
  
  # 图片选择需要依赖的库
  pod 'JGActionSheet', '~> 1.0.5'
  pod 'CJMedia/CJValidateAuthorizationUtil', '~> 0.0.5'
  pod 'CJMedia/MySingleImagePickerController', '~> 0.0.5'
  pod 'CJMedia/CJPhotoBrowser', '~> 0.0.5'
  pod 'CJFile/CJFileManager', '~> 0.0.8'
  pod 'CJNetwork/AFNetworkingBaseComponent', '~> 0.1.3' #用于登录
  pod 'CJNetwork/AFNetworkingUploadComponent', '~> 0.1.3' #需要8.0以上
  
  # 网页
  pod 'WebViewJavascriptBridge', '~> 6.0.2'
  
  # 基本的第三方库
  pod 'MJExtension', '~> 3.0.13'
  pod 'Mantle', '~> 2.1.0'
  
  pod 'YYText', '~> 1.0.7'
  
end

target 'CJUIKitDemoTests' do
   
end
